---
title: "Large-scale LC-MS data plotting with lcmsPlot"
output:
  BiocStyle::html_document:
    toc: true
    toc_depth: 2  
    number_sections: true  
    toc_float: true
vignette: >
  %\VignetteIndexEntry{basic_plotting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: references.bib
csl: biomed-central.csl
---

```{r setup, include = FALSE}
knitr::opts_knit$set(
  root.dir = dirname(getwd())
)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r init, message = FALSE, echo = FALSE, results = "hide"}
library(BiocStyle)
library(xcms)
library(MsExperiment)
library(patchwork)
library(openxlsx)
library(lcmsPlot)
```


```{r}
root_dir <- "Z:/data/PrecisionTox/Studies/02_Phase2/002_IUB_F_Dmelanogaster/IUB_F_Dmelanogaster_AE"
metadata <- read.xlsx(file.path(root_dir, "data", "metadata", "metadata.xlsx"), sheet = "metaData_HILIC_POS")
```

```{r}
metadata_example <- metadata %>% head(n = 50)

raw_files <- file.path(root_dir, "data", "HILIC_POS", "mzml", paste0(metadata_example$Sample, ".mzML"))

p = lcmsPlot(raw_files, sample_id_column = "Sample", metadata = metadata_example, batch_size = 10) +
  lcmsPlot::chromatogram(ppm = 5, rt_tol = 10, aggregation_fun = "max") +
  lcmsPlot::facets(facets = "sample_id", ncol = 5)

pdf("test.pdf", width = 10, height = 5)
iterate_plot_batches(p, function (plot_item) {
  print(plot_item)
})
dev.off()
```

```{r}
raw_files <- list.files(file.path(root_dir, "data", "HILIC_POS", "mzml"), pattern = "\\.mzML", full.names = TRUE)

p = lcmsPlot(raw_files, sample_id_column = "Sample", metadata = metadata, batch_size = 4) +
  lcmsPlot::chromatogram(
    features = rbind(c(mz = 71.0684439, rt = 419)),
    ppm = 5,
    rt_tol = 10
  ) +
  lcmsPlot::mass_trace() +
  lcmsPlot::spectra(mode = "closest", rt = 419) +
  lcmsPlot::facets(facets = "sample_id", ncol = 4)
p

p = next_plot(p)
p

p = next_plot(p)
p
```
